//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceX.SvcTipoTelefone {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcTipoTelefone.ISvcTipoTelefone")]
    public interface ISvcTipoTelefone {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Complete", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/CompleteResponse")]
        void Complete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Complete", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/CompleteResponse")]
        System.Threading.Tasks.Task CompleteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Salvar", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/SalvarResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TipoTelefone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TelsClients))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Agendamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Profissional))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Especialidade))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Servico))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TelsProfissionals))]
        void Salvar(Infraestrutura.Entity cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Salvar", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/SalvarResponse")]
        System.Threading.Tasks.Task SalvarAsync(Infraestrutura.Entity cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/SalvarEntities", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/SalvarEntitiesRespons" +
            "e")]
        void SalvarEntities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/SalvarEntities", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/SalvarEntitiesRespons" +
            "e")]
        System.Threading.Tasks.Task SalvarEntitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/AdicionarEntity", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/AdicionarEntityRespon" +
            "se")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TipoTelefone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TelsClients))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Agendamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Profissional))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Especialidade))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Servico))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TelsProfissionals))]
        void AdicionarEntity(Infraestrutura.Entity cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/AdicionarEntity", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/AdicionarEntityRespon" +
            "se")]
        System.Threading.Tasks.Task AdicionarEntityAsync(Infraestrutura.Entity cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Adicionar", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/AdicionarResponse")]
        void Adicionar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Adicionar", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/AdicionarResponse")]
        System.Threading.Tasks.Task AdicionarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Remover", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/RemoverResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TipoTelefone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TelsClients))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Cliente))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Agendamento))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Profissional))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Especialidade))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.Servico))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Model.TelsProfissionals))]
        void Remover(Infraestrutura.Entity cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Remover", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/RemoverResponse")]
        System.Threading.Tasks.Task RemoverAsync(Infraestrutura.Entity cls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/RemoverEntities", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/RemoverEntitiesRespon" +
            "se")]
        void RemoverEntities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/RemoverEntities", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/RemoverEntitiesRespon" +
            "se")]
        System.Threading.Tasks.Task RemoverEntitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Paginate", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/PaginateResponse")]
        Infraestrutura.Entity[] Paginate(int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/Paginate", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository/PaginateResponse")]
        System.Threading.Tasks.Task<Infraestrutura.Entity[]> PaginateAsync(int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoTelefone/SetAddEntity", ReplyAction="http://tempuri.org/ISvcTipoTelefone/SetAddEntityResponse")]
        void SetAddEntity(Model.TipoTelefone param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoTelefone/SetAddEntity", ReplyAction="http://tempuri.org/ISvcTipoTelefone/SetAddEntityResponse")]
        System.Threading.Tasks.Task SetAddEntityAsync(Model.TipoTelefone param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoTelefone/SetAddUpdateEntity", ReplyAction="http://tempuri.org/ISvcTipoTelefone/SetAddUpdateEntityResponse")]
        void SetAddUpdateEntity(Model.TipoTelefone param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoTelefone/SetAddUpdateEntity", ReplyAction="http://tempuri.org/ISvcTipoTelefone/SetAddUpdateEntityResponse")]
        System.Threading.Tasks.Task SetAddUpdateEntityAsync(Model.TipoTelefone param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoTelefone/SetAddRemoveEntity", ReplyAction="http://tempuri.org/ISvcTipoTelefone/SetAddRemoveEntityResponse")]
        void SetAddRemoveEntity(Model.TipoTelefone param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvcTipoTelefone/SetAddRemoveEntity", ReplyAction="http://tempuri.org/ISvcTipoTelefone/SetAddRemoveEntityResponse")]
        System.Threading.Tasks.Task SetAddRemoveEntityAsync(Model.TipoTelefone param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcTipoTelefoneChannel : ServiceX.SvcTipoTelefone.ISvcTipoTelefone, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcTipoTelefoneClient : System.ServiceModel.ClientBase<ServiceX.SvcTipoTelefone.ISvcTipoTelefone>, ServiceX.SvcTipoTelefone.ISvcTipoTelefone {
        
        public SvcTipoTelefoneClient() {
        }
        
        public SvcTipoTelefoneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcTipoTelefoneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcTipoTelefoneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcTipoTelefoneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Complete() {
            base.Channel.Complete();
        }
        
        public System.Threading.Tasks.Task CompleteAsync() {
            return base.Channel.CompleteAsync();
        }
        
        public void Salvar(Infraestrutura.Entity cls) {
            base.Channel.Salvar(cls);
        }
        
        public System.Threading.Tasks.Task SalvarAsync(Infraestrutura.Entity cls) {
            return base.Channel.SalvarAsync(cls);
        }
        
        public void SalvarEntities() {
            base.Channel.SalvarEntities();
        }
        
        public System.Threading.Tasks.Task SalvarEntitiesAsync() {
            return base.Channel.SalvarEntitiesAsync();
        }
        
        public void AdicionarEntity(Infraestrutura.Entity cls) {
            base.Channel.AdicionarEntity(cls);
        }
        
        public System.Threading.Tasks.Task AdicionarEntityAsync(Infraestrutura.Entity cls) {
            return base.Channel.AdicionarEntityAsync(cls);
        }
        
        public void Adicionar() {
            base.Channel.Adicionar();
        }
        
        public System.Threading.Tasks.Task AdicionarAsync() {
            return base.Channel.AdicionarAsync();
        }
        
        public void Remover(Infraestrutura.Entity cls) {
            base.Channel.Remover(cls);
        }
        
        public System.Threading.Tasks.Task RemoverAsync(Infraestrutura.Entity cls) {
            return base.Channel.RemoverAsync(cls);
        }
        
        public void RemoverEntities() {
            base.Channel.RemoverEntities();
        }
        
        public System.Threading.Tasks.Task RemoverEntitiesAsync() {
            return base.Channel.RemoverEntitiesAsync();
        }
        
        public Infraestrutura.Entity[] Paginate(int pageIndex, int pageSize) {
            return base.Channel.Paginate(pageIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<Infraestrutura.Entity[]> PaginateAsync(int pageIndex, int pageSize) {
            return base.Channel.PaginateAsync(pageIndex, pageSize);
        }
        
        public void SetAddEntity(Model.TipoTelefone param) {
            base.Channel.SetAddEntity(param);
        }
        
        public System.Threading.Tasks.Task SetAddEntityAsync(Model.TipoTelefone param) {
            return base.Channel.SetAddEntityAsync(param);
        }
        
        public void SetAddUpdateEntity(Model.TipoTelefone param) {
            base.Channel.SetAddUpdateEntity(param);
        }
        
        public System.Threading.Tasks.Task SetAddUpdateEntityAsync(Model.TipoTelefone param) {
            return base.Channel.SetAddUpdateEntityAsync(param);
        }
        
        public void SetAddRemoveEntity(Model.TipoTelefone param) {
            base.Channel.SetAddRemoveEntity(param);
        }
        
        public System.Threading.Tasks.Task SetAddRemoveEntityAsync(Model.TipoTelefone param) {
            return base.Channel.SetAddRemoveEntityAsync(param);
        }
    }
}
