//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using Infraestrutura;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente : Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Agendamentos = new HashSet<Agendamento>();
            this.TelsClients = new HashSet<TelsClients>();
        }
        
        public string Nome { get; set; }
        public string CPF { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string sexo { get; set; }
        public string estado_civil { get; set; }
        public string email { get; set; }
        public string observacoes { get; set; }
        public string endereco { get; set; }
        public Nullable<int> numero_end { get; set; }
        public Nullable<int> CEP { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agendamento> Agendamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelsClients> TelsClients { get; set; }
    }
}
