//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using Infraestrutura;
    using System.ComponentModel.DataAnnotations;

    public partial class PerfilAcesso : Entity
    {
        public int cod_tela { get; set; }
        public int cod_perfil { get; set; }
        public int permissao { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Tela Tela { get; set; }
    }
}
