//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using Infraestrutura;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Telefones_Prof")]
    public partial class TelsProfissionals : Entity
    {
        public Nullable<int> DDD { get; set; }
        public Nullable<int> numero { get; set; }
        public Nullable<int> cod_tipo_telefone { get; set; }
        public Nullable<int> cod_profissional { get; set; }
    
        public virtual Profissional Profissional { get; set; }
        public virtual TipoTelefone TipoTelefone { get; set; }
    }
}
