//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using Infraestrutura;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;

    [KnownType(typeof(TelsClients))]
    [Table("Telefones_Cli")]
    public partial class TelsClients : Entity
    {
        [DataMember]
        public Nullable<int> DDD { get; set; }
        [DataMember]
        public Nullable<int> numero { get; set; }
        [DataMember]
        public Nullable<int> cod_tipo_telefone { get; set; }
        [DataMember]
        public Nullable<int> cod_cliente { get; set; }
        [DataMember]
        public virtual Cliente Cliente { get; set; }
        [DataMember]
        public virtual TipoTelefone TipoTelefone { get; set; }
    }
}
