//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServiceXY.SvcTipoTelefone {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IEntityOfint", Namespace="servicex.com", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Entity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.TelsClients))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Cliente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Agendamento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Profissional))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Especialidade))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Servico))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.TelsProfissionals))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.TipoTelefone))]
    public partial class IEntityOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ConcurrencyTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ConcurrencyToken {
            get {
                return this.ConcurrencyTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrencyTokenField, value) != true)) {
                    this.ConcurrencyTokenField = value;
                    this.RaisePropertyChanged("ConcurrencyToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod {
            get {
                return this.codField;
            }
            set {
                if ((this.codField.Equals(value) != true)) {
                    this.codField = value;
                    this.RaisePropertyChanged("cod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="servicex.com", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.TelsClients))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Cliente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Agendamento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Profissional))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Especialidade))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.Servico))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.TelsProfissionals))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceXY.SvcTipoTelefone.TipoTelefone))]
    public partial class Entity : WebApiServiceXY.SvcTipoTelefone.IEntityOfint {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelsClients", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TelsClients : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.TipoTelefone TipoTelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cod_tipo_telefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DDD {
            get {
                return this.DDDField;
            }
            set {
                if ((this.DDDField.Equals(value) != true)) {
                    this.DDDField = value;
                    this.RaisePropertyChanged("DDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.TipoTelefone TipoTelefone {
            get {
                return this.TipoTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTelefoneField, value) != true)) {
                    this.TipoTelefoneField = value;
                    this.RaisePropertyChanged("TipoTelefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cod_tipo_telefone {
            get {
                return this.cod_tipo_telefoneField;
            }
            set {
                if ((this.cod_tipo_telefoneField.Equals(value) != true)) {
                    this.cod_tipo_telefoneField = value;
                    this.RaisePropertyChanged("cod_tipo_telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Cliente : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Agendamento[] AgendamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.TelsClients[] TelsClientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> data_nascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estado_civilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numero_endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Agendamento[] Agendamentos {
            get {
                return this.AgendamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.AgendamentosField, value) != true)) {
                    this.AgendamentosField = value;
                    this.RaisePropertyChanged("Agendamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((this.CEPField.Equals(value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.TelsClients[] TelsClients {
            get {
                return this.TelsClientsField;
            }
            set {
                if ((object.ReferenceEquals(this.TelsClientsField, value) != true)) {
                    this.TelsClientsField = value;
                    this.RaisePropertyChanged("TelsClients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroField, value) != true)) {
                    this.bairroField = value;
                    this.RaisePropertyChanged("bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.cidadeField, value) != true)) {
                    this.cidadeField = value;
                    this.RaisePropertyChanged("cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> data_nascimento {
            get {
                return this.data_nascimentoField;
            }
            set {
                if ((this.data_nascimentoField.Equals(value) != true)) {
                    this.data_nascimentoField = value;
                    this.RaisePropertyChanged("data_nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_civil {
            get {
                return this.estado_civilField;
            }
            set {
                if ((object.ReferenceEquals(this.estado_civilField, value) != true)) {
                    this.estado_civilField = value;
                    this.RaisePropertyChanged("estado_civil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numero_end {
            get {
                return this.numero_endField;
            }
            set {
                if ((this.numero_endField.Equals(value) != true)) {
                    this.numero_endField = value;
                    this.RaisePropertyChanged("numero_end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacoesField, value) != true)) {
                    this.observacoesField = value;
                    this.RaisePropertyChanged("observacoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneField, value) != true)) {
                    this.telefoneField = value;
                    this.RaisePropertyChanged("telefone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agendamento", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Agendamento : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Profissional ProfissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Servico ServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_profissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_servicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime data_agendamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime horario_agendamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacoesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Profissional Profissional {
            get {
                return this.ProfissionalField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfissionalField, value) != true)) {
                    this.ProfissionalField = value;
                    this.RaisePropertyChanged("Profissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Servico Servico {
            get {
                return this.ServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicoField, value) != true)) {
                    this.ServicoField = value;
                    this.RaisePropertyChanged("Servico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_profissional {
            get {
                return this.cod_profissionalField;
            }
            set {
                if ((this.cod_profissionalField.Equals(value) != true)) {
                    this.cod_profissionalField = value;
                    this.RaisePropertyChanged("cod_profissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_servico {
            get {
                return this.cod_servicoField;
            }
            set {
                if ((this.cod_servicoField.Equals(value) != true)) {
                    this.cod_servicoField = value;
                    this.RaisePropertyChanged("cod_servico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime data_agendamento {
            get {
                return this.data_agendamentoField;
            }
            set {
                if ((this.data_agendamentoField.Equals(value) != true)) {
                    this.data_agendamentoField = value;
                    this.RaisePropertyChanged("data_agendamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime horario_agendamento {
            get {
                return this.horario_agendamentoField;
            }
            set {
                if ((this.horario_agendamentoField.Equals(value) != true)) {
                    this.horario_agendamentoField = value;
                    this.RaisePropertyChanged("horario_agendamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacoesField, value) != true)) {
                    this.observacoesField = value;
                    this.RaisePropertyChanged("observacoes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profissional", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Profissional : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Agendamento[] AgendamentoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Especialidade EspecialidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Servico[] ServicoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.TelsProfissionals[] TelsProfissionalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_especialidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> data_nascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numero_endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Agendamento[] Agendamentoes {
            get {
                return this.AgendamentoesField;
            }
            set {
                if ((object.ReferenceEquals(this.AgendamentoesField, value) != true)) {
                    this.AgendamentoesField = value;
                    this.RaisePropertyChanged("Agendamentoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Especialidade Especialidade {
            get {
                return this.EspecialidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadeField, value) != true)) {
                    this.EspecialidadeField = value;
                    this.RaisePropertyChanged("Especialidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Servico[] Servicoes {
            get {
                return this.ServicoesField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicoesField, value) != true)) {
                    this.ServicoesField = value;
                    this.RaisePropertyChanged("Servicoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.TelsProfissionals[] TelsProfissionals {
            get {
                return this.TelsProfissionalsField;
            }
            set {
                if ((object.ReferenceEquals(this.TelsProfissionalsField, value) != true)) {
                    this.TelsProfissionalsField = value;
                    this.RaisePropertyChanged("TelsProfissionals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroField, value) != true)) {
                    this.bairroField = value;
                    this.RaisePropertyChanged("bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.cidadeField, value) != true)) {
                    this.cidadeField = value;
                    this.RaisePropertyChanged("cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_especialidade {
            get {
                return this.cod_especialidadeField;
            }
            set {
                if ((this.cod_especialidadeField.Equals(value) != true)) {
                    this.cod_especialidadeField = value;
                    this.RaisePropertyChanged("cod_especialidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> data_nascimento {
            get {
                return this.data_nascimentoField;
            }
            set {
                if ((this.data_nascimentoField.Equals(value) != true)) {
                    this.data_nascimentoField = value;
                    this.RaisePropertyChanged("data_nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numero_end {
            get {
                return this.numero_endField;
            }
            set {
                if ((this.numero_endField.Equals(value) != true)) {
                    this.numero_endField = value;
                    this.RaisePropertyChanged("numero_end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacoesField, value) != true)) {
                    this.observacoesField = value;
                    this.RaisePropertyChanged("observacoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneField, value) != true)) {
                    this.telefoneField = value;
                    this.RaisePropertyChanged("telefone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Especialidade", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Especialidade : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Profissional[] ProfissionalsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Profissional[] Profissionals {
            get {
                return this.ProfissionalsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfissionalsField, value) != true)) {
                    this.ProfissionalsField = value;
                    this.RaisePropertyChanged("Profissionals");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servico", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Servico : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Agendamento[] AgendamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Profissional ProfissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TempoExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_profissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observacoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Agendamento[] Agendamentos {
            get {
                return this.AgendamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.AgendamentosField, value) != true)) {
                    this.AgendamentosField = value;
                    this.RaisePropertyChanged("Agendamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Profissional Profissional {
            get {
                return this.ProfissionalField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfissionalField, value) != true)) {
                    this.ProfissionalField = value;
                    this.RaisePropertyChanged("Profissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TempoExecucao {
            get {
                return this.TempoExecucaoField;
            }
            set {
                if ((this.TempoExecucaoField.Equals(value) != true)) {
                    this.TempoExecucaoField = value;
                    this.RaisePropertyChanged("TempoExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_profissional {
            get {
                return this.cod_profissionalField;
            }
            set {
                if ((this.cod_profissionalField.Equals(value) != true)) {
                    this.cod_profissionalField = value;
                    this.RaisePropertyChanged("cod_profissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.descricaoField, value) != true)) {
                    this.descricaoField = value;
                    this.RaisePropertyChanged("descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.observacoesField, value) != true)) {
                    this.observacoesField = value;
                    this.RaisePropertyChanged("observacoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipoServico {
            get {
                return this.tipoServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoServicoField, value) != true)) {
                    this.tipoServicoField = value;
                    this.RaisePropertyChanged("tipoServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> valor {
            get {
                return this.valorField;
            }
            set {
                if ((this.valorField.Equals(value) != true)) {
                    this.valorField = value;
                    this.RaisePropertyChanged("valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelsProfissionals", Namespace="http://schemas.datacontract.org/2004/07/Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TelsProfissionals : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.Profissional ProfissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.TipoTelefone TipoTelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cod_profissionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cod_tipo_telefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> numeroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DDD {
            get {
                return this.DDDField;
            }
            set {
                if ((this.DDDField.Equals(value) != true)) {
                    this.DDDField = value;
                    this.RaisePropertyChanged("DDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.Profissional Profissional {
            get {
                return this.ProfissionalField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfissionalField, value) != true)) {
                    this.ProfissionalField = value;
                    this.RaisePropertyChanged("Profissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.TipoTelefone TipoTelefone {
            get {
                return this.TipoTelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTelefoneField, value) != true)) {
                    this.TipoTelefoneField = value;
                    this.RaisePropertyChanged("TipoTelefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cod_profissional {
            get {
                return this.cod_profissionalField;
            }
            set {
                if ((this.cod_profissionalField.Equals(value) != true)) {
                    this.cod_profissionalField = value;
                    this.RaisePropertyChanged("cod_profissional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cod_tipo_telefone {
            get {
                return this.cod_tipo_telefoneField;
            }
            set {
                if ((this.cod_tipo_telefoneField.Equals(value) != true)) {
                    this.cod_tipo_telefoneField = value;
                    this.RaisePropertyChanged("cod_tipo_telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTelefone", Namespace="servicex.com", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class TipoTelefone : WebApiServiceXY.SvcTipoTelefone.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.TelsClients[] TelsClientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.TelsProfissionals[] TelsProfissionalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desc_tipo_telefoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.TelsClients[] TelsClients {
            get {
                return this.TelsClientsField;
            }
            set {
                if ((object.ReferenceEquals(this.TelsClientsField, value) != true)) {
                    this.TelsClientsField = value;
                    this.RaisePropertyChanged("TelsClients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.TelsProfissionals[] TelsProfissionals {
            get {
                return this.TelsProfissionalsField;
            }
            set {
                if ((object.ReferenceEquals(this.TelsProfissionalsField, value) != true)) {
                    this.TelsProfissionalsField = value;
                    this.RaisePropertyChanged("TelsProfissionals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc_tipo_telefone {
            get {
                return this.desc_tipo_telefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.desc_tipo_telefoneField, value) != true)) {
                    this.desc_tipo_telefoneField = value;
                    this.RaisePropertyChanged("desc_tipo_telefone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectContractOfTipoTelefonechDCM5K5", Namespace="http://schemas.datacontract.org/2004/07/Wcf_ServiceX.Generic")]
    [System.SerializableAttribute()]
    public partial class ObjectContractOfTipoTelefonechDCM5K5 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebApiServiceXY.SvcTipoTelefone.TipoTelefone[] PaginatedListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebApiServiceXY.SvcTipoTelefone.TipoTelefone[] PaginatedList {
            get {
                return this.PaginatedListField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginatedListField, value) != true)) {
                    this.PaginatedListField = value;
                    this.RaisePropertyChanged("PaginatedList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://Wcf-ServiceX/services/ISvcTipoTelefone/", ConfigurationName="SvcTipoTelefone.ISvcTipoTelefone")]
    public interface ISvcTipoTelefone {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message CompleteRequest does not match the default value (https://Wcf-ServiceX/services/ISvcTipoTelefone/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Complete" +
            "", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Complete" +
            "Response")]
        WebApiServiceXY.SvcTipoTelefone.CompleteResponse Complete(WebApiServiceXY.SvcTipoTelefone.CompleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message AddRequest does not match the default value (https://Wcf-ServiceX/services/ISvcTipoTelefone/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Add", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/AddRespo" +
            "nse")]
        WebApiServiceXY.SvcTipoTelefone.AddResponse Add(WebApiServiceXY.SvcTipoTelefone.AddRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message UpdateRequest does not match the default value (https://Wcf-ServiceX/services/ISvcTipoTelefone/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Update", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/UpdateRe" +
            "sponse")]
        WebApiServiceXY.SvcTipoTelefone.UpdateResponse Update(WebApiServiceXY.SvcTipoTelefone.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message RemoveRequest does not match the default value (https://Wcf-ServiceX/services/ISvcTipoTelefone/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Remove", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/RemoveRe" +
            "sponse")]
        WebApiServiceXY.SvcTipoTelefone.RemoveResponse Remove(WebApiServiceXY.SvcTipoTelefone.RemoveRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message PaginateRequest does not match the default value (https://Wcf-ServiceX/services/ISvcTipoTelefone/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Paginate" +
            "", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Paginate" +
            "Response")]
        WebApiServiceXY.SvcTipoTelefone.PaginateResponse Paginate(WebApiServiceXY.SvcTipoTelefone.PaginateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message PaginateEntityRequest does not match the default value (https://Wcf-ServiceX/services/ISvcTipoTelefone/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Paginate" +
            "Entity", ReplyAction="http://tempuri.org/IGenericServiceOf_TipoTelefoneRepository_TipoTelefone/Paginate" +
            "EntityResponse")]
        WebApiServiceXY.SvcTipoTelefone.PaginateEntityResponse PaginateEntity(WebApiServiceXY.SvcTipoTelefone.PaginateEntityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Complete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompleteRequest {
        
        public CompleteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CompleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CompleteResponse {
        
        public CompleteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceXY.SvcTipoTelefone.TipoTelefone param;
        
        public AddRequest() {
        }
        
        public AddRequest(WebApiServiceXY.SvcTipoTelefone.TipoTelefone param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        public AddResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceXY.SvcTipoTelefone.TipoTelefone param;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(WebApiServiceXY.SvcTipoTelefone.TipoTelefone param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResponse {
        
        public UpdateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceXY.SvcTipoTelefone.TipoTelefone param;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(WebApiServiceXY.SvcTipoTelefone.TipoTelefone param) {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveResponse {
        
        public RemoveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Paginate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaginateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        public PaginateRequest() {
        }
        
        public PaginateRequest(int pageIndex, int pageSize) {
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaginateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaginateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceXY.SvcTipoTelefone.Entity[] PaginateResult;
        
        public PaginateResponse() {
        }
        
        public PaginateResponse(WebApiServiceXY.SvcTipoTelefone.Entity[] PaginateResult) {
            this.PaginateResult = PaginateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaginateEntity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaginateEntityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string orderby;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool desc;
        
        public PaginateEntityRequest() {
        }
        
        public PaginateEntityRequest(int pageIndex, int pageSize, string orderby, bool desc) {
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.orderby = orderby;
            this.desc = desc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaginateEntityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaginateEntityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceXY.SvcTipoTelefone.ObjectContractOfTipoTelefonechDCM5K5 PaginateEntityResult;
        
        public PaginateEntityResponse() {
        }
        
        public PaginateEntityResponse(WebApiServiceXY.SvcTipoTelefone.ObjectContractOfTipoTelefonechDCM5K5 PaginateEntityResult) {
            this.PaginateEntityResult = PaginateEntityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISvcTipoTelefoneChannel : WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SvcTipoTelefoneClient : System.ServiceModel.ClientBase<WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone>, WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone {
        
        public SvcTipoTelefoneClient() {
        }
        
        public SvcTipoTelefoneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SvcTipoTelefoneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcTipoTelefoneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SvcTipoTelefoneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiServiceXY.SvcTipoTelefone.CompleteResponse WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone.Complete(WebApiServiceXY.SvcTipoTelefone.CompleteRequest request) {
            return base.Channel.Complete(request);
        }
        
        public void Complete() {
            WebApiServiceXY.SvcTipoTelefone.CompleteRequest inValue = new WebApiServiceXY.SvcTipoTelefone.CompleteRequest();
            WebApiServiceXY.SvcTipoTelefone.CompleteResponse retVal = ((WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone)(this)).Complete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiServiceXY.SvcTipoTelefone.AddResponse WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone.Add(WebApiServiceXY.SvcTipoTelefone.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(WebApiServiceXY.SvcTipoTelefone.TipoTelefone param) {
            WebApiServiceXY.SvcTipoTelefone.AddRequest inValue = new WebApiServiceXY.SvcTipoTelefone.AddRequest();
            inValue.param = param;
            WebApiServiceXY.SvcTipoTelefone.AddResponse retVal = ((WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiServiceXY.SvcTipoTelefone.UpdateResponse WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone.Update(WebApiServiceXY.SvcTipoTelefone.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(WebApiServiceXY.SvcTipoTelefone.TipoTelefone param) {
            WebApiServiceXY.SvcTipoTelefone.UpdateRequest inValue = new WebApiServiceXY.SvcTipoTelefone.UpdateRequest();
            inValue.param = param;
            WebApiServiceXY.SvcTipoTelefone.UpdateResponse retVal = ((WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiServiceXY.SvcTipoTelefone.RemoveResponse WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone.Remove(WebApiServiceXY.SvcTipoTelefone.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public void Remove(WebApiServiceXY.SvcTipoTelefone.TipoTelefone param) {
            WebApiServiceXY.SvcTipoTelefone.RemoveRequest inValue = new WebApiServiceXY.SvcTipoTelefone.RemoveRequest();
            inValue.param = param;
            WebApiServiceXY.SvcTipoTelefone.RemoveResponse retVal = ((WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone)(this)).Remove(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiServiceXY.SvcTipoTelefone.PaginateResponse WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone.Paginate(WebApiServiceXY.SvcTipoTelefone.PaginateRequest request) {
            return base.Channel.Paginate(request);
        }
        
        public WebApiServiceXY.SvcTipoTelefone.Entity[] Paginate(int pageIndex, int pageSize) {
            WebApiServiceXY.SvcTipoTelefone.PaginateRequest inValue = new WebApiServiceXY.SvcTipoTelefone.PaginateRequest();
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            WebApiServiceXY.SvcTipoTelefone.PaginateResponse retVal = ((WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone)(this)).Paginate(inValue);
            return retVal.PaginateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApiServiceXY.SvcTipoTelefone.PaginateEntityResponse WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone.PaginateEntity(WebApiServiceXY.SvcTipoTelefone.PaginateEntityRequest request) {
            return base.Channel.PaginateEntity(request);
        }
        
        public WebApiServiceXY.SvcTipoTelefone.ObjectContractOfTipoTelefonechDCM5K5 PaginateEntity(int pageIndex, int pageSize, string orderby, bool desc) {
            WebApiServiceXY.SvcTipoTelefone.PaginateEntityRequest inValue = new WebApiServiceXY.SvcTipoTelefone.PaginateEntityRequest();
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.orderby = orderby;
            inValue.desc = desc;
            WebApiServiceXY.SvcTipoTelefone.PaginateEntityResponse retVal = ((WebApiServiceXY.SvcTipoTelefone.ISvcTipoTelefone)(this)).PaginateEntity(inValue);
            return retVal.PaginateEntityResult;
        }
    }
}
