//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts
{
    using System.Runtime.Serialization;

    [DataContract]
    public class PerfilAcesso : EntityContracts
    {
        [DataMember]
        public int cod_tela { get; set; }

        [DataMember]
        public int cod_perfil { get; set; }

        [DataMember]
        public int permissao { get; set; }

        [DataMember]
        public virtual Perfil Perfil { get; set; }

        [DataMember]
        public virtual Tela Tela { get; set; }
    }
}
