//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts
{

    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class Profissional : EntityContracts
    {
        public Profissional()
        {
            this.Agendamentoes = new HashSet<Agendamento>();
            this.Servicoes = new HashSet<Servico>();
            this.TelsProfissionals = new HashSet<TelsProfissionals>();
        }

        [DataMember]
        public string Nome { get; set; }

        [DataMember]
        public string CPF { get; set; }

        [DataMember]
        public Nullable<System.DateTime> data_nascimento { get; set; }

        [DataMember]
        public string sexo { get; set; }

        [DataMember]
        public string email { get; set; }

        [DataMember]
        public int cod_especialidade { get; set; }

        [DataMember]
        public string observacoes { get; set; }

        [DataMember]
        public string endereco { get; set; }

        [DataMember]
        public Nullable<int> numero_end { get; set; }

        [DataMember]
        public string CEP { get; set; }

        [DataMember]
        public string bairro { get; set; }

        [DataMember]
        public string cidade { get; set; }

        [DataMember]
        public string estado { get; set; }

        [DataMember]
        public string telefone { get; set; }

        [DataMember]
        public string celular { get; set; }

        [DataMember]
        public virtual ICollection<Agendamento> Agendamentoes { get; set; }

        [DataMember]
        public virtual Especialidade Especialidade { get; set; }

        [DataMember]
        public virtual ICollection<Servico> Servicoes { get; set; }

        [DataMember]
        public virtual ICollection<TelsProfissionals> TelsProfissionals { get; set; }
    }
}
