//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contracts
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class Tela : EntityContracts
    {
        public Tela()
        {
            this.PerfilAcessos = new HashSet<PerfilAcesso>();
        }

        [DataMember]
        public string tela1 { get; set; }

        [DataMember]
        public virtual ICollection<PerfilAcesso> PerfilAcessos { get; set; }
    }
}
