//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiServiceX.ServiceXRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceXY")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IEntityOfint", Namespace="http://schemas.datacontract.org/2004/07/Infraestrutura")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApiServiceX.ServiceXRef.Entity))]
    public partial class IEntityOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/Infraestrutura")]
    [System.SerializableAttribute()]
    public partial class Entity : WebApiServiceX.ServiceXRef.IEntityOfint {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceXRef.IServiceXY")]
    public interface IServiceXY {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/GetData", ReplyAction="http://tempuri.org/IServiceXY/GetDataResponse")]
        WebApiServiceX.ServiceXRef.GetDataResponse GetData(WebApiServiceX.ServiceXRef.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/GetData", ReplyAction="http://tempuri.org/IServiceXY/GetDataResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.GetDataResponse> GetDataAsync(WebApiServiceX.ServiceXRef.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceXY/GetDataUsingDataContractResponse")]
        WebApiServiceX.ServiceXRef.GetDataUsingDataContractResponse GetDataUsingDataContract(WebApiServiceX.ServiceXRef.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceXY/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(WebApiServiceX.ServiceXRef.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/InsertPersistente", ReplyAction="http://tempuri.org/IServiceXY/InsertPersistenteResponse")]
        WebApiServiceX.ServiceXRef.InsertPersistenteResponse InsertPersistente(WebApiServiceX.ServiceXRef.InsertPersistenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/InsertPersistente", ReplyAction="http://tempuri.org/IServiceXY/InsertPersistenteResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.InsertPersistenteResponse> InsertPersistenteAsync(WebApiServiceX.ServiceXRef.InsertPersistenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/FindByID", ReplyAction="http://tempuri.org/IServiceXY/FindByIDResponse")]
        WebApiServiceX.ServiceXRef.FindByIDResponse FindByID(WebApiServiceX.ServiceXRef.FindByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/FindByID", ReplyAction="http://tempuri.org/IServiceXY/FindByIDResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.FindByIDResponse> FindByIDAsync(WebApiServiceX.ServiceXRef.FindByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/UpdatePersistente", ReplyAction="http://tempuri.org/IServiceXY/UpdatePersistenteResponse")]
        WebApiServiceX.ServiceXRef.UpdatePersistenteResponse UpdatePersistente(WebApiServiceX.ServiceXRef.UpdatePersistenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/UpdatePersistente", ReplyAction="http://tempuri.org/IServiceXY/UpdatePersistenteResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.UpdatePersistenteResponse> UpdatePersistenteAsync(WebApiServiceX.ServiceXRef.UpdatePersistenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/DeletePersistente", ReplyAction="http://tempuri.org/IServiceXY/DeletePersistenteResponse")]
        WebApiServiceX.ServiceXRef.DeletePersistenteResponse DeletePersistente(WebApiServiceX.ServiceXRef.DeletePersistenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/DeletePersistente", ReplyAction="http://tempuri.org/IServiceXY/DeletePersistenteResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.DeletePersistenteResponse> DeletePersistenteAsync(WebApiServiceX.ServiceXRef.DeletePersistenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Salvar", ReplyAction="http://tempuri.org/IServiceXY/SalvarResponse")]
        WebApiServiceX.ServiceXRef.SalvarResponse Salvar(WebApiServiceX.ServiceXRef.SalvarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Salvar", ReplyAction="http://tempuri.org/IServiceXY/SalvarResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.SalvarResponse> SalvarAsync(WebApiServiceX.ServiceXRef.SalvarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Adicionar", ReplyAction="http://tempuri.org/IServiceXY/AdicionarResponse")]
        WebApiServiceX.ServiceXRef.AdicionarResponse Adicionar(WebApiServiceX.ServiceXRef.AdicionarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Adicionar", ReplyAction="http://tempuri.org/IServiceXY/AdicionarResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.AdicionarResponse> AdicionarAsync(WebApiServiceX.ServiceXRef.AdicionarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Remover", ReplyAction="http://tempuri.org/IServiceXY/RemoverResponse")]
        WebApiServiceX.ServiceXRef.RemoverResponse Remover(WebApiServiceX.ServiceXRef.RemoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Remover", ReplyAction="http://tempuri.org/IServiceXY/RemoverResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.RemoverResponse> RemoverAsync(WebApiServiceX.ServiceXRef.RemoverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Dispose", ReplyAction="http://tempuri.org/IServiceXY/DisposeResponse")]
        WebApiServiceX.ServiceXRef.DisposeResponse Dispose(WebApiServiceX.ServiceXRef.DisposeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Dispose", ReplyAction="http://tempuri.org/IServiceXY/DisposeResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.DisposeResponse> DisposeAsync(WebApiServiceX.ServiceXRef.DisposeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Paginate", ReplyAction="http://tempuri.org/IServiceXY/PaginateResponse")]
        WebApiServiceX.ServiceXRef.PaginateResponse Paginate(WebApiServiceX.ServiceXRef.PaginateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceXY/Paginate", ReplyAction="http://tempuri.org/IServiceXY/PaginateResponse")]
        System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.PaginateResponse> PaginateAsync(WebApiServiceX.ServiceXRef.PaginateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.CompositeType composite;
        
        public GetDataUsingDataContractRequest() {
        }
        
        public GetDataUsingDataContractRequest(WebApiServiceX.ServiceXRef.CompositeType composite) {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse() {
        }
        
        public GetDataUsingDataContractResponse(WebApiServiceX.ServiceXRef.CompositeType GetDataUsingDataContractResult) {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertPersistente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertPersistenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity entity;
        
        public InsertPersistenteRequest() {
        }
        
        public InsertPersistenteRequest(WebApiServiceX.ServiceXRef.Entity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertPersistenteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertPersistenteResponse {
        
        public InsertPersistenteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public FindByIDRequest() {
        }
        
        public FindByIDRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindByIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity FindByIDResult;
        
        public FindByIDResponse() {
        }
        
        public FindByIDResponse(WebApiServiceX.ServiceXRef.Entity FindByIDResult) {
            this.FindByIDResult = FindByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePersistente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePersistenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity entidade;
        
        public UpdatePersistenteRequest() {
        }
        
        public UpdatePersistenteRequest(WebApiServiceX.ServiceXRef.Entity entidade) {
            this.entidade = entidade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePersistenteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePersistenteResponse {
        
        public UpdatePersistenteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePersistente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePersistenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity entidade;
        
        public DeletePersistenteRequest() {
        }
        
        public DeletePersistenteRequest(WebApiServiceX.ServiceXRef.Entity entidade) {
            this.entidade = entidade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePersistenteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeletePersistenteResponse {
        
        public DeletePersistenteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Salvar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalvarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity cls;
        
        public SalvarRequest() {
        }
        
        public SalvarRequest(WebApiServiceX.ServiceXRef.Entity cls) {
            this.cls = cls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalvarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalvarResponse {
        
        public SalvarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Adicionar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdicionarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity cls;
        
        public AdicionarRequest() {
        }
        
        public AdicionarRequest(WebApiServiceX.ServiceXRef.Entity cls) {
            this.cls = cls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AdicionarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AdicionarResponse {
        
        public AdicionarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remover", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity cls;
        
        public RemoverRequest() {
        }
        
        public RemoverRequest(WebApiServiceX.ServiceXRef.Entity cls) {
            this.cls = cls;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoverResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoverResponse {
        
        public RemoverResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Dispose", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisposeRequest {
        
        public DisposeRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DisposeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DisposeResponse {
        
        public DisposeResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Paginate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaginateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        public PaginateRequest() {
        }
        
        public PaginateRequest(int pageIndex, int pageSize) {
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PaginateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PaginateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebApiServiceX.ServiceXRef.Entity[] PaginateResult;
        
        public PaginateResponse() {
        }
        
        public PaginateResponse(WebApiServiceX.ServiceXRef.Entity[] PaginateResult) {
            this.PaginateResult = PaginateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceXYChannel : WebApiServiceX.ServiceXRef.IServiceXY, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceXYClient : System.ServiceModel.ClientBase<WebApiServiceX.ServiceXRef.IServiceXY>, WebApiServiceX.ServiceXRef.IServiceXY {
        
        public ServiceXYClient() {
        }
        
        public ServiceXYClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceXYClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceXYClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceXYClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApiServiceX.ServiceXRef.GetDataResponse GetData(WebApiServiceX.ServiceXRef.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.GetDataResponse> GetDataAsync(WebApiServiceX.ServiceXRef.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.GetDataUsingDataContractResponse GetDataUsingDataContract(WebApiServiceX.ServiceXRef.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(WebApiServiceX.ServiceXRef.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.InsertPersistenteResponse InsertPersistente(WebApiServiceX.ServiceXRef.InsertPersistenteRequest request) {
            return base.Channel.InsertPersistente(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.InsertPersistenteResponse> InsertPersistenteAsync(WebApiServiceX.ServiceXRef.InsertPersistenteRequest request) {
            return base.Channel.InsertPersistenteAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.FindByIDResponse FindByID(WebApiServiceX.ServiceXRef.FindByIDRequest request) {
            return base.Channel.FindByID(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.FindByIDResponse> FindByIDAsync(WebApiServiceX.ServiceXRef.FindByIDRequest request) {
            return base.Channel.FindByIDAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.UpdatePersistenteResponse UpdatePersistente(WebApiServiceX.ServiceXRef.UpdatePersistenteRequest request) {
            return base.Channel.UpdatePersistente(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.UpdatePersistenteResponse> UpdatePersistenteAsync(WebApiServiceX.ServiceXRef.UpdatePersistenteRequest request) {
            return base.Channel.UpdatePersistenteAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.DeletePersistenteResponse DeletePersistente(WebApiServiceX.ServiceXRef.DeletePersistenteRequest request) {
            return base.Channel.DeletePersistente(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.DeletePersistenteResponse> DeletePersistenteAsync(WebApiServiceX.ServiceXRef.DeletePersistenteRequest request) {
            return base.Channel.DeletePersistenteAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.SalvarResponse Salvar(WebApiServiceX.ServiceXRef.SalvarRequest request) {
            return base.Channel.Salvar(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.SalvarResponse> SalvarAsync(WebApiServiceX.ServiceXRef.SalvarRequest request) {
            return base.Channel.SalvarAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.AdicionarResponse Adicionar(WebApiServiceX.ServiceXRef.AdicionarRequest request) {
            return base.Channel.Adicionar(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.AdicionarResponse> AdicionarAsync(WebApiServiceX.ServiceXRef.AdicionarRequest request) {
            return base.Channel.AdicionarAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.RemoverResponse Remover(WebApiServiceX.ServiceXRef.RemoverRequest request) {
            return base.Channel.Remover(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.RemoverResponse> RemoverAsync(WebApiServiceX.ServiceXRef.RemoverRequest request) {
            return base.Channel.RemoverAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.DisposeResponse Dispose(WebApiServiceX.ServiceXRef.DisposeRequest request) {
            return base.Channel.Dispose(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.DisposeResponse> DisposeAsync(WebApiServiceX.ServiceXRef.DisposeRequest request) {
            return base.Channel.DisposeAsync(request);
        }
        
        public WebApiServiceX.ServiceXRef.PaginateResponse Paginate(WebApiServiceX.ServiceXRef.PaginateRequest request) {
            return base.Channel.Paginate(request);
        }
        
        public System.Threading.Tasks.Task<WebApiServiceX.ServiceXRef.PaginateResponse> PaginateAsync(WebApiServiceX.ServiceXRef.PaginateRequest request) {
            return base.Channel.PaginateAsync(request);
        }
    }
}
