//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiceX.WebSvcTipoTelefone {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'EndpointReference' from namespace 'http://www.w3.org/2005/08/addressing' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSHttpContextBinding_ISvcTipoTelefone", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IEntityOfint))]
    public partial class SvcTipoTelefone : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddEntitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalvarOperationCompleted;
        
        private System.Threading.SendOrPostCallback SalvarEntitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdicionarEntityOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdicionarOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdicionarEntitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoverEntitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaginateOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeServiceInstanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompletesServiceInstanceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SvcTipoTelefone() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::ServiceX.Properties.Settings.Default.ServiceX_WebSvcTipoTelefone_SvcTipoTelefone;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddEntitiesCompletedEventHandler AddEntitiesCompleted;
        
        /// <remarks/>
        public event SetCompletedEventHandler SetCompleted;
        
        /// <remarks/>
        public event SalvarCompletedEventHandler SalvarCompleted;
        
        /// <remarks/>
        public event SalvarEntitiesCompletedEventHandler SalvarEntitiesCompleted;
        
        /// <remarks/>
        public event AdicionarEntityCompletedEventHandler AdicionarEntityCompleted;
        
        /// <remarks/>
        public event AdicionarCompletedEventHandler AdicionarCompleted;
        
        /// <remarks/>
        public event AdicionarEntitiesCompletedEventHandler AdicionarEntitiesCompleted;
        
        /// <remarks/>
        public event RemoverCompletedEventHandler RemoverCompleted;
        
        /// <remarks/>
        public event RemoverEntitiesCompletedEventHandler RemoverEntitiesCompleted;
        
        /// <remarks/>
        public event PaginateCompletedEventHandler PaginateCompleted;
        
        /// <remarks/>
        public event InitializeServiceCompletedEventHandler InitializeServiceCompleted;
        
        /// <remarks/>
        public event InitializeServiceInstanceCompletedEventHandler InitializeServiceInstanceCompleted;
        
        /// <remarks/>
        public event CompletesServiceInstanceCompletedEventHandler CompletesServiceInstanceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/AddEntities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddEntities([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entity _entity) {
            this.Invoke("AddEntities", new object[] {
                        _entity});
        }
        
        /// <remarks/>
        public void AddEntitiesAsync(Entity _entity) {
            this.AddEntitiesAsync(_entity, null);
        }
        
        /// <remarks/>
        public void AddEntitiesAsync(Entity _entity, object userState) {
            if ((this.AddEntitiesOperationCompleted == null)) {
                this.AddEntitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEntitiesOperationCompleted);
            }
            this.InvokeAsync("AddEntities", new object[] {
                        _entity}, this.AddEntitiesOperationCompleted, userState);
        }
        
        private void OnAddEntitiesOperationCompleted(object arg) {
            if ((this.AddEntitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEntitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/Set", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Set([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entity _entity) {
            this.Invoke("Set", new object[] {
                        _entity});
        }
        
        /// <remarks/>
        public void SetAsync(Entity _entity) {
            this.SetAsync(_entity, null);
        }
        
        /// <remarks/>
        public void SetAsync(Entity _entity, object userState) {
            if ((this.SetOperationCompleted == null)) {
                this.SetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetOperationCompleted);
            }
            this.InvokeAsync("Set", new object[] {
                        _entity}, this.SetOperationCompleted, userState);
        }
        
        private void OnSetOperationCompleted(object arg) {
            if ((this.SetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/Salvar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Salvar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entity cls) {
            this.Invoke("Salvar", new object[] {
                        cls});
        }
        
        /// <remarks/>
        public void SalvarAsync(Entity cls) {
            this.SalvarAsync(cls, null);
        }
        
        /// <remarks/>
        public void SalvarAsync(Entity cls, object userState) {
            if ((this.SalvarOperationCompleted == null)) {
                this.SalvarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarOperationCompleted);
            }
            this.InvokeAsync("Salvar", new object[] {
                        cls}, this.SalvarOperationCompleted, userState);
        }
        
        private void OnSalvarOperationCompleted(object arg) {
            if ((this.SalvarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/SalvarEntities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SalvarEntities() {
            this.Invoke("SalvarEntities", new object[0]);
        }
        
        /// <remarks/>
        public void SalvarEntitiesAsync() {
            this.SalvarEntitiesAsync(null);
        }
        
        /// <remarks/>
        public void SalvarEntitiesAsync(object userState) {
            if ((this.SalvarEntitiesOperationCompleted == null)) {
                this.SalvarEntitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSalvarEntitiesOperationCompleted);
            }
            this.InvokeAsync("SalvarEntities", new object[0], this.SalvarEntitiesOperationCompleted, userState);
        }
        
        private void OnSalvarEntitiesOperationCompleted(object arg) {
            if ((this.SalvarEntitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SalvarEntitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/AdicionarEntity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AdicionarEntity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entity cls) {
            this.Invoke("AdicionarEntity", new object[] {
                        cls});
        }
        
        /// <remarks/>
        public void AdicionarEntityAsync(Entity cls) {
            this.AdicionarEntityAsync(cls, null);
        }
        
        /// <remarks/>
        public void AdicionarEntityAsync(Entity cls, object userState) {
            if ((this.AdicionarEntityOperationCompleted == null)) {
                this.AdicionarEntityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarEntityOperationCompleted);
            }
            this.InvokeAsync("AdicionarEntity", new object[] {
                        cls}, this.AdicionarEntityOperationCompleted, userState);
        }
        
        private void OnAdicionarEntityOperationCompleted(object arg) {
            if ((this.AdicionarEntityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarEntityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/Adicionar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Adicionar() {
            this.Invoke("Adicionar", new object[0]);
        }
        
        /// <remarks/>
        public void AdicionarAsync() {
            this.AdicionarAsync(null);
        }
        
        /// <remarks/>
        public void AdicionarAsync(object userState) {
            if ((this.AdicionarOperationCompleted == null)) {
                this.AdicionarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarOperationCompleted);
            }
            this.InvokeAsync("Adicionar", new object[0], this.AdicionarOperationCompleted, userState);
        }
        
        private void OnAdicionarOperationCompleted(object arg) {
            if ((this.AdicionarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/AdicionarEntities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AdicionarEntities() {
            this.Invoke("AdicionarEntities", new object[0]);
        }
        
        /// <remarks/>
        public void AdicionarEntitiesAsync() {
            this.AdicionarEntitiesAsync(null);
        }
        
        /// <remarks/>
        public void AdicionarEntitiesAsync(object userState) {
            if ((this.AdicionarEntitiesOperationCompleted == null)) {
                this.AdicionarEntitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdicionarEntitiesOperationCompleted);
            }
            this.InvokeAsync("AdicionarEntities", new object[0], this.AdicionarEntitiesOperationCompleted, userState);
        }
        
        private void OnAdicionarEntitiesOperationCompleted(object arg) {
            if ((this.AdicionarEntitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdicionarEntitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/Remover", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Remover([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entity cls) {
            this.Invoke("Remover", new object[] {
                        cls});
        }
        
        /// <remarks/>
        public void RemoverAsync(Entity cls) {
            this.RemoverAsync(cls, null);
        }
        
        /// <remarks/>
        public void RemoverAsync(Entity cls, object userState) {
            if ((this.RemoverOperationCompleted == null)) {
                this.RemoverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverOperationCompleted);
            }
            this.InvokeAsync("Remover", new object[] {
                        cls}, this.RemoverOperationCompleted, userState);
        }
        
        private void OnRemoverOperationCompleted(object arg) {
            if ((this.RemoverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/RemoverEntities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoverEntities() {
            this.Invoke("RemoverEntities", new object[0]);
        }
        
        /// <remarks/>
        public void RemoverEntitiesAsync() {
            this.RemoverEntitiesAsync(null);
        }
        
        /// <remarks/>
        public void RemoverEntitiesAsync(object userState) {
            if ((this.RemoverEntitiesOperationCompleted == null)) {
                this.RemoverEntitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoverEntitiesOperationCompleted);
            }
            this.InvokeAsync("RemoverEntities", new object[0], this.RemoverEntitiesOperationCompleted, userState);
        }
        
        private void OnRemoverEntitiesOperationCompleted(object arg) {
            if ((this.RemoverEntitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoverEntitiesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IGenericService/Paginate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Infraestrutura")]
        public Entity[] Paginate(int pageIndex, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageIndexSpecified, int pageSize, [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageSizeSpecified) {
            object[] results = this.Invoke("Paginate", new object[] {
                        pageIndex,
                        pageIndexSpecified,
                        pageSize,
                        pageSizeSpecified});
            return ((Entity[])(results[0]));
        }
        
        /// <remarks/>
        public void PaginateAsync(int pageIndex, bool pageIndexSpecified, int pageSize, bool pageSizeSpecified) {
            this.PaginateAsync(pageIndex, pageIndexSpecified, pageSize, pageSizeSpecified, null);
        }
        
        /// <remarks/>
        public void PaginateAsync(int pageIndex, bool pageIndexSpecified, int pageSize, bool pageSizeSpecified, object userState) {
            if ((this.PaginateOperationCompleted == null)) {
                this.PaginateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaginateOperationCompleted);
            }
            this.InvokeAsync("Paginate", new object[] {
                        pageIndex,
                        pageIndexSpecified,
                        pageSize,
                        pageSizeSpecified}, this.PaginateOperationCompleted, userState);
        }
        
        private void OnPaginateOperationCompleted(object arg) {
            if ((this.PaginateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaginateCompleted(this, new PaginateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISvcTipoTelefone/InitializeService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InitializeService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] TipoTelefone _tipoTelefone) {
            this.Invoke("InitializeService", new object[] {
                        _tipoTelefone});
        }
        
        /// <remarks/>
        public void InitializeServiceAsync(TipoTelefone _tipoTelefone) {
            this.InitializeServiceAsync(_tipoTelefone, null);
        }
        
        /// <remarks/>
        public void InitializeServiceAsync(TipoTelefone _tipoTelefone, object userState) {
            if ((this.InitializeServiceOperationCompleted == null)) {
                this.InitializeServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeServiceOperationCompleted);
            }
            this.InvokeAsync("InitializeService", new object[] {
                        _tipoTelefone}, this.InitializeServiceOperationCompleted, userState);
        }
        
        private void OnInitializeServiceOperationCompleted(object arg) {
            if ((this.InitializeServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeServiceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISvcTipoTelefone/InitializeServiceInstance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InitializeServiceInstance() {
            this.Invoke("InitializeServiceInstance", new object[0]);
        }
        
        /// <remarks/>
        public void InitializeServiceInstanceAsync() {
            this.InitializeServiceInstanceAsync(null);
        }
        
        /// <remarks/>
        public void InitializeServiceInstanceAsync(object userState) {
            if ((this.InitializeServiceInstanceOperationCompleted == null)) {
                this.InitializeServiceInstanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeServiceInstanceOperationCompleted);
            }
            this.InvokeAsync("InitializeServiceInstance", new object[0], this.InitializeServiceInstanceOperationCompleted, userState);
        }
        
        private void OnInitializeServiceInstanceOperationCompleted(object arg) {
            if ((this.InitializeServiceInstanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeServiceInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISvcTipoTelefone/CompletesServiceInstance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CompletesServiceInstance() {
            this.Invoke("CompletesServiceInstance", new object[0]);
        }
        
        /// <remarks/>
        public void CompletesServiceInstanceAsync() {
            this.CompletesServiceInstanceAsync(null);
        }
        
        /// <remarks/>
        public void CompletesServiceInstanceAsync(object userState) {
            if ((this.CompletesServiceInstanceOperationCompleted == null)) {
                this.CompletesServiceInstanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompletesServiceInstanceOperationCompleted);
            }
            this.InvokeAsync("CompletesServiceInstance", new object[0], this.CompletesServiceInstanceOperationCompleted, userState);
        }
        
        private void OnCompletesServiceInstanceOperationCompleted(object arg) {
            if ((this.CompletesServiceInstanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompletesServiceInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelsProfissionals))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Servico))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Especialidade))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Profissional))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Agendamento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelsClients))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoTelefone))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Infraestrutura")]
    public partial class Entity : IEntityOfint {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelsProfissionals))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Servico))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Especialidade))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Profissional))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Agendamento))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TelsClients))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TipoTelefone))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Infraestrutura")]
    public partial class IEntityOfint {
        
        private int codk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<cod>k__BackingField")]
        public int codk__BackingField {
            get {
                return this.codk__BackingFieldField;
            }
            set {
                this.codk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class TelsProfissionals : Entity {
        
        private System.Nullable<int> dDDField;
        
        private bool dDDFieldSpecified;
        
        private Profissional profissionalField;
        
        private TipoTelefone tipoTelefoneField;
        
        private System.Nullable<int> cod_profissionalField;
        
        private bool cod_profissionalFieldSpecified;
        
        private System.Nullable<int> cod_tipo_telefoneField;
        
        private bool cod_tipo_telefoneFieldSpecified;
        
        private System.Nullable<int> numeroField;
        
        private bool numeroFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DDD {
            get {
                return this.dDDField;
            }
            set {
                this.dDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DDDSpecified {
            get {
                return this.dDDFieldSpecified;
            }
            set {
                this.dDDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Profissional Profissional {
            get {
                return this.profissionalField;
            }
            set {
                this.profissionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoTelefone TipoTelefone {
            get {
                return this.tipoTelefoneField;
            }
            set {
                this.tipoTelefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> cod_profissional {
            get {
                return this.cod_profissionalField;
            }
            set {
                this.cod_profissionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_profissionalSpecified {
            get {
                return this.cod_profissionalFieldSpecified;
            }
            set {
                this.cod_profissionalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> cod_tipo_telefone {
            get {
                return this.cod_tipo_telefoneField;
            }
            set {
                this.cod_tipo_telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_tipo_telefoneSpecified {
            get {
                return this.cod_tipo_telefoneFieldSpecified;
            }
            set {
                this.cod_tipo_telefoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Profissional : Entity {
        
        private Agendamento[] agendamentoesField;
        
        private string cEPField;
        
        private string cPFField;
        
        private Especialidade especialidadeField;
        
        private string nomeField;
        
        private Servico[] servicoesField;
        
        private TelsProfissionals[] telsProfissionalsField;
        
        private string bairroField;
        
        private string celularField;
        
        private string cidadeField;
        
        private int cod_especialidadeField;
        
        private bool cod_especialidadeFieldSpecified;
        
        private System.Nullable<System.DateTime> data_nascimentoField;
        
        private bool data_nascimentoFieldSpecified;
        
        private string emailField;
        
        private string enderecoField;
        
        private string estadoField;
        
        private System.Nullable<int> numero_endField;
        
        private bool numero_endFieldSpecified;
        
        private string observacoesField;
        
        private string sexoField;
        
        private string telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Agendamento[] Agendamentoes {
            get {
                return this.agendamentoesField;
            }
            set {
                this.agendamentoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Especialidade Especialidade {
            get {
                return this.especialidadeField;
            }
            set {
                this.especialidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Servico[] Servicoes {
            get {
                return this.servicoesField;
            }
            set {
                this.servicoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TelsProfissionals[] TelsProfissionals {
            get {
                return this.telsProfissionalsField;
            }
            set {
                this.telsProfissionalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public int cod_especialidade {
            get {
                return this.cod_especialidadeField;
            }
            set {
                this.cod_especialidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_especialidadeSpecified {
            get {
                return this.cod_especialidadeFieldSpecified;
            }
            set {
                this.cod_especialidadeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> data_nascimento {
            get {
                return this.data_nascimentoField;
            }
            set {
                this.data_nascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool data_nascimentoSpecified {
            get {
                return this.data_nascimentoFieldSpecified;
            }
            set {
                this.data_nascimentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> numero_end {
            get {
                return this.numero_endField;
            }
            set {
                this.numero_endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numero_endSpecified {
            get {
                return this.numero_endFieldSpecified;
            }
            set {
                this.numero_endFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                this.observacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Agendamento : Entity {
        
        private Cliente clienteField;
        
        private Profissional profissionalField;
        
        private Servico servicoField;
        
        private int cod_clienteField;
        
        private bool cod_clienteFieldSpecified;
        
        private int cod_profissionalField;
        
        private bool cod_profissionalFieldSpecified;
        
        private int cod_servicoField;
        
        private bool cod_servicoFieldSpecified;
        
        private System.DateTime data_agendamentoField;
        
        private bool data_agendamentoFieldSpecified;
        
        private System.DateTime horario_agendamentoField;
        
        private bool horario_agendamentoFieldSpecified;
        
        private string observacoesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Profissional Profissional {
            get {
                return this.profissionalField;
            }
            set {
                this.profissionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Servico Servico {
            get {
                return this.servicoField;
            }
            set {
                this.servicoField = value;
            }
        }
        
        /// <remarks/>
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                this.cod_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_clienteSpecified {
            get {
                return this.cod_clienteFieldSpecified;
            }
            set {
                this.cod_clienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int cod_profissional {
            get {
                return this.cod_profissionalField;
            }
            set {
                this.cod_profissionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_profissionalSpecified {
            get {
                return this.cod_profissionalFieldSpecified;
            }
            set {
                this.cod_profissionalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int cod_servico {
            get {
                return this.cod_servicoField;
            }
            set {
                this.cod_servicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_servicoSpecified {
            get {
                return this.cod_servicoFieldSpecified;
            }
            set {
                this.cod_servicoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime data_agendamento {
            get {
                return this.data_agendamentoField;
            }
            set {
                this.data_agendamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool data_agendamentoSpecified {
            get {
                return this.data_agendamentoFieldSpecified;
            }
            set {
                this.data_agendamentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime horario_agendamento {
            get {
                return this.horario_agendamentoField;
            }
            set {
                this.horario_agendamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horario_agendamentoSpecified {
            get {
                return this.horario_agendamentoFieldSpecified;
            }
            set {
                this.horario_agendamentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                this.observacoesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Cliente : Entity {
        
        private Agendamento[] agendamentosField;
        
        private System.Nullable<int> cEPField;
        
        private bool cEPFieldSpecified;
        
        private string cPFField;
        
        private string nomeField;
        
        private TelsClients[] telsClientsField;
        
        private string bairroField;
        
        private string celularField;
        
        private string cidadeField;
        
        private System.Nullable<System.DateTime> data_nascimentoField;
        
        private bool data_nascimentoFieldSpecified;
        
        private string emailField;
        
        private string enderecoField;
        
        private string estadoField;
        
        private string estado_civilField;
        
        private System.Nullable<int> numero_endField;
        
        private bool numero_endFieldSpecified;
        
        private string observacoesField;
        
        private string sexoField;
        
        private string telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Agendamento[] Agendamentos {
            get {
                return this.agendamentosField;
            }
            set {
                this.agendamentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CEPSpecified {
            get {
                return this.cEPFieldSpecified;
            }
            set {
                this.cEPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TelsClients[] TelsClients {
            get {
                return this.telsClientsField;
            }
            set {
                this.telsClientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> data_nascimento {
            get {
                return this.data_nascimentoField;
            }
            set {
                this.data_nascimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool data_nascimentoSpecified {
            get {
                return this.data_nascimentoFieldSpecified;
            }
            set {
                this.data_nascimentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string estado_civil {
            get {
                return this.estado_civilField;
            }
            set {
                this.estado_civilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> numero_end {
            get {
                return this.numero_endField;
            }
            set {
                this.numero_endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numero_endSpecified {
            get {
                return this.numero_endFieldSpecified;
            }
            set {
                this.numero_endFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                this.observacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class TelsClients : Entity {
        
        private Cliente clienteField;
        
        private System.Nullable<int> dDDField;
        
        private bool dDDFieldSpecified;
        
        private TipoTelefone tipoTelefoneField;
        
        private System.Nullable<int> cod_clienteField;
        
        private bool cod_clienteFieldSpecified;
        
        private System.Nullable<int> cod_tipo_telefoneField;
        
        private bool cod_tipo_telefoneFieldSpecified;
        
        private System.Nullable<int> numeroField;
        
        private bool numeroFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DDD {
            get {
                return this.dDDField;
            }
            set {
                this.dDDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DDDSpecified {
            get {
                return this.dDDFieldSpecified;
            }
            set {
                this.dDDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TipoTelefone TipoTelefone {
            get {
                return this.tipoTelefoneField;
            }
            set {
                this.tipoTelefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                this.cod_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_clienteSpecified {
            get {
                return this.cod_clienteFieldSpecified;
            }
            set {
                this.cod_clienteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> cod_tipo_telefone {
            get {
                return this.cod_tipo_telefoneField;
            }
            set {
                this.cod_tipo_telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_tipo_telefoneSpecified {
            get {
                return this.cod_tipo_telefoneFieldSpecified;
            }
            set {
                this.cod_tipo_telefoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroSpecified {
            get {
                return this.numeroFieldSpecified;
            }
            set {
                this.numeroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class TipoTelefone : Entity {
        
        private TelsClients[] telsClientsField;
        
        private TelsProfissionals[] telsProfissionalsField;
        
        private string desc_tipo_telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TelsClients[] TelsClients {
            get {
                return this.telsClientsField;
            }
            set {
                this.telsClientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TelsProfissionals[] TelsProfissionals {
            get {
                return this.telsProfissionalsField;
            }
            set {
                this.telsProfissionalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desc_tipo_telefone {
            get {
                return this.desc_tipo_telefoneField;
            }
            set {
                this.desc_tipo_telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Servico : Entity {
        
        private Agendamento[] agendamentosField;
        
        private string nomeField;
        
        private Profissional profissionalField;
        
        private System.DateTime tempoExecucaoField;
        
        private bool tempoExecucaoFieldSpecified;
        
        private int cod_profissionalField;
        
        private bool cod_profissionalFieldSpecified;
        
        private string descricaoField;
        
        private string observacoesField;
        
        private string tipoServicoField;
        
        private System.Nullable<decimal> valorField;
        
        private bool valorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Agendamento[] Agendamentos {
            get {
                return this.agendamentosField;
            }
            set {
                this.agendamentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Profissional Profissional {
            get {
                return this.profissionalField;
            }
            set {
                this.profissionalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TempoExecucao {
            get {
                return this.tempoExecucaoField;
            }
            set {
                this.tempoExecucaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TempoExecucaoSpecified {
            get {
                return this.tempoExecucaoFieldSpecified;
            }
            set {
                this.tempoExecucaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int cod_profissional {
            get {
                return this.cod_profissionalField;
            }
            set {
                this.cod_profissionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cod_profissionalSpecified {
            get {
                return this.cod_profissionalFieldSpecified;
            }
            set {
                this.cod_profissionalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string observacoes {
            get {
                return this.observacoesField;
            }
            set {
                this.observacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoServico {
            get {
                return this.tipoServicoField;
            }
            set {
                this.tipoServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Model")]
    public partial class Especialidade : Entity {
        
        private string descricaoField;
        
        private Profissional[] profissionalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Profissional[] Profissionals {
            get {
                return this.profissionalsField;
            }
            set {
                this.profissionalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AddEntitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SalvarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SalvarEntitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AdicionarEntityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AdicionarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AdicionarEntitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RemoverCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void RemoverEntitiesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PaginateCompletedEventHandler(object sender, PaginateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaginateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaginateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Entity[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Entity[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InitializeServiceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InitializeServiceInstanceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void CompletesServiceInstanceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591